gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Welcome::
	.string "Oh, wait!\p"
	.string "Before you go, a message from this\n"
	.string "hack's creator:\p"
	.string "Welcome to Pokémon Emerald Double!\p"
	.string "This is a difficulty hack with modern\n"
	.string "mechanics, many quality of life\l"
	.string "changes, and massive Pokémon variety!\p"
	.string "You can build your team using almost\n"
	.string "any Pokémon up to gen nine!\p"
	.string "Before you get started, you'll need\n"
	.string "to choose a difficulty setting.\p"
	.string "Currently you can choose between\n"
	.string "Easy, Normal or Champion Mode.\p"
	.string "Please select a mode to learn more\n"
	.string "about it.$"

gText_EasyMode::
	.string "In Easy Mode, Trainers won't have\n"
	.string "EVs, so you won't need to worry\l"
	.string "about your own Pokémon's stats.\p"
	.string "Only Boss NPCs will only have items\n"
	.string "equipped to their Ace Pokémon.\p"
	.string "This difficulty is recommended if\n"
	.string "you're new to difficulty hacks, or\l"
	.string "if you don't want to deal with EVs.\p"
	.string "However, there are restrictions:\p"
	.string "You will have access to the bag in\n"
	.string "Trainer Battles, and you can choose\l"
	.string "between Set or Shift battle styles.\p"
	.string "So, would you like to play on\n"
	.string "{COLOR GREEN}Easy Mode{COLOR DARK_GRAY}?$"

gText_NormalMode::
	.string "In Normal Mode, Trainers will have EV-\n"
	.string "trained Pokémon as the game progresses.\p"
	.string "All trainers will have items eqipped\n"
	.string "to their Pokémon and the shift\l"
	.string "battle style is disabled.\n"
	.string "This difficulty is recommended for\n"
	.string "experienced players.\p"
	.string "So, would you like to play on\n"
	.string "{COLOR BLUE}Normal Mode{COLOR DARK_GRAY}?$"

gText_ChampionMode::
	.string "Champion Mode is the hardest difficulty.\n"
	.string "Every single Trainer has custom EVs.\p"
	.string "It also has these restrictions:\p"
	.string "You can't access the bag in Trainer\n"
	.string "Battles, and the Shift battle style is\l"
	.string "disabled.\p"
	.string "Good strategy and a balanced team\n"
	.string "are more important in this mode.\p"
	.string "So, would you like to play on\n"
	.string "{COLOR RED}Champion Mode{COLOR DARK_GRAY}?$"

gText_WhichDifficulty::
	.string "Which difficulty would you like to\n"
	.string "play on?$"
